table CS
	lineageTag: 4cd170e6-1dd9-4fb0-b9fa-b7a7e07fdda0

	column 'CCS (code)'
		dataType: string
		lineageTag: 821ee6be-bf8d-4f65-b5f4-724b3d0a3e3c
		summarizeBy: none
		sourceColumn: CCS (code)

		annotation SummarizationSetBy = Automatic

	column RÉCEPTION
		dataType: string
		lineageTag: 4d7cfe69-a721-4c59-957e-4e3032509a60
		summarizeBy: none
		sourceColumn: RÉCEPTION

		annotation SummarizationSetBy = Automatic

	column CONCESSION
		dataType: string
		lineageTag: ac025308-330a-4379-ab6b-dbeac4995394
		summarizeBy: none
		sourceColumn: CONCESSION

		annotation SummarizationSetBy = Automatic

	column 'Cs std'
		dataType: string
		lineageTag: 06f79e93-258e-4cff-a654-1796716fd113
		summarizeBy: none
		sourceColumn: Cs std

		annotation SummarizationSetBy = Automatic

	column 'Ouverte au chrono'
		dataType: int64
		formatString: 0
		lineageTag: 889b68f5-84d4-490d-86b8-a4acf361b24f
		summarizeBy: sum
		sourceColumn: Ouverte au chrono

		annotation SummarizationSetBy = Automatic

	partition CS = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("G:\Drive partagés\Service MACS\02 - Projets & Performance\Groupe\Dash'Op\03 - PowerBI\données\Tables ref.xlsx"), null, true),
				    CS_Sheet = Source{[Item="CS",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(CS_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié1" = Table.TransformColumnTypes(#"En-têtes promus",{{"CCS (code)", type text}, {"RÉCEPTION", type text}, {"CONCESSION", type text}, {"Cs std", type text}, {"Ouverte au chrono", Int64.Type}})
				in
				    #"Type modifié1"

	annotation PBI_ResultType = Table

