table Meca
	lineageTag: d6fcd1cb-8767-40d1-886f-44470135b34e

	column CONCESSION
		dataType: string
		lineageTag: afa015d2-01c8-4b34-88be-f4af98f35ae5
		summarizeBy: none
		sourceColumn: CONCESSION

		annotation SummarizationSetBy = Automatic

	column 'RÉCEPTION Meca'
		dataType: string
		lineageTag: 1a2a90c3-5335-40b5-8396-fcff2c91ef06
		summarizeBy: none
		sourceColumn: RÉCEPTION Meca

		annotation SummarizationSetBy = Automatic

	column RÉCEPTION
		dataType: string
		lineageTag: b85f3426-f422-454f-9e8f-051c8ced7e81
		summarizeBy: none
		sourceColumn: RÉCEPTION

		annotation SummarizationSetBy = Automatic

	partition Meca = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("G:\Drive partagés\Service MACS\02 - Projets & Performance\Groupe\Dash'Op\03 - PowerBI\données\Tables ref.xlsx"), null, true),
				    Meca_Sheet = Source{[Item="Meca",Kind="Sheet"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(Meca_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"En-têtes promus" = Table.PromoteHeaders(#"Type modifié", [PromoteAllScalars=true]),
				    #"Type modifié1" = Table.TransformColumnTypes(#"En-têtes promus",{{"CONCESSION", type text}, {"RÉCEPTION Meca", type text}, {"RÉCEPTION", type text}})
				in
				    #"Type modifié1"

	annotation PBI_ResultType = Table

